lc:
  upload:
    path: D:/static/
server:
  port: 8081
  address: 127.0.0.1
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: food
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
  resources:
    static-locations: classpath:/static/,file:${lc.upload.path}
  mvc:
    static-path-pattern: /res/**


mybatis:
  config-location: classpath:mybatis-config.xml
